#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_date = "2024-05-02"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "647d17e2-7d2c-46c8-9bf5-dad5da994604"

[vars]
IS_CLOUDFLARE_WORKER = "true"

[dev]
port = 5000
